### ISSUE TITLE
DOCUMENT_ROOT problem with virtual hosting

### ISSUE THREAD

**Issue by tmewett** [Self-Evident/OneFileCMS#21]
By default, $DOC_ROOT uses `$_SERVER['DOCUMENT_ROOT'].'/'`. This creates problems on virtually-hosted website as this variable points to the completely wrong place, causing it to throw up lots of errors and limit functionality.

I have managed to fix it for myself by replacing all instances of `$_SERVER['DOCUMENT_ROOT']` with `dirname(__FILE__)` (there aren't very many)

Are there any reasons why this is not used instead?

**Comment by Self-Evident** [comment]
If this is still an issue for anyone, with a current version of OneFileCMS, please post a new ticket.  Thanks!
