### ISSUE TITLE
Permissions Awareness

### ISSUE THREAD

**Issue by billymail** [Self-Evident/OneFileCMS#31]
It'd be slicker if OneFileCMS was aware of what it could/couldn't edit.

For instance, if folder has 777, it would show as editable, otherwise it would show as viewable, with no save options

**Comment by Self-Evident** [comment]
This should be do-able.  I'll look into it. (But, that sometimes takes a while :)  Thanks for the suggestion!

**Comment by Self-Evident** [comment]
Done!  
And it only took less than three months!  ... 
...Give or take a few years???? :)
