### ISSUE TITLE
Thanks for this project.This is not an issue but one feature.

### ISSUE THREAD

**Issue by webmumbai** [Self-Evident/OneFileCMS#36]
Thanks for this project.and that too is free.This is not an issue but one feature.Since I do not know where to submit new feature request.I am sending in this section.In case of file editing text/html/php if it will show the "Line Number" it will be great enhancement for online editing.  
Once again thanks for such nice & well crafted script.

**Comment by Self-Evident** [comment]
Sorry for the delay - I've been away from this project for a bit. But, for what it's worth, line-numbers will be added shortly - in the next day or so.

**Comment by Self-Evident** [comment]
Ok, maybe not quite the next day or so then, but now maybe in the next day or so...  :)

**Comment by Self-Evident** [comment]
Line numbers added!
The one current side effect is that word wrapping is now break-all, instead of break-word.  That is, at the end of a line, the line will wrap even in the middle of a word, instead of at the first prior white-space.  That is next on the agenda, but this is done.
