### ISSUE TITLE
Feature request - pass file name

### ISSUE THREAD

**Issue by jwzumwalt** [Self-Evident/OneFileCMS#38]
It would be nice to be able to pass a specific file name for the editor to open.
i.e.  onefilecms.php?fname=test.htm

Tanks for the hard work and your consideration to this suggestion :)

**Comment by Self-Evident** [comment]
This is a good suggestion.  I'll tackle this after looking at some of the other issues (I'm a bit behind).  If you, or anybody, have any suggestions on  the implementation, that would be welcome.

**Comment by Self-Evident** [comment]
Actually, (and I don't know why I didn't realize this on first reading), you can manually enter a path and file name.  That's actually how OFCMS passes some info to itself.  For example:

http://www.example.com/onefilecms.php?i=some_directory/&f=H-sample.html&p=edit

The "i" parameter means directory "index" - the directory path to the file (relative to the root of the website) .  The "f" parameter is the file's name.  And "p=edit" means, well, edit page.  :)

Hope that helps!

**Comment by jwzumwalt** [comment]
Sooo... a "help" tab is needed so that a user can access this information... right?
