### ISSUE TITLE
$config_stypes not working: Warning: in_array() expects parameter 2 to be array, null given in (..)\onefilecms.php on line 1890

### ISSUE THREAD

**Issue by Freekers** [Self-Evident/OneFileCMS#39]
Hi!

I'm trying to use to restrict the listing of certain filetypes. I've set it up like so:
$config_stypes = "txt,text";

But when I do so, I get greeted by this error:
Warning: in_array() expects parameter 2 to be array, null given in (..)\onefilecms.php on line 1890

Am I doing something wrong or is this a bug?

Thanks!

**Comment by Self-Evident** [comment]
Sorry for the delayed response.

Well, there was an issue, but it seems to have been resolved as of version 3.5.18. (~June 9, 2016)

**Comment by Self-Evident** [comment]
Sorry for the delayed response.

Well, there was an issue, but it seems to have been resolved as of version 3.5.18. (~June 9, 2016)

Closed.
