### ISSUE TITLE
No logs, please

### ISSUE THREAD

**Issue by zu** [Self-Evident/OneFileCMS#44]
While log files are generally a very good thing, I don't want to have "clutter" left-over.
The way I'm using OneFileCMS is not as a CMS but just to edit some config files directly on the server without the need to download the file first.

Is there a configuration parameter to not log anything or send the log by mail after the session ends and delete it from server?

**Comment by Self-Evident** [comment]
"Is there a configuration parameter to not log anything"
Yes - as far as OFCMS can control.  However, there is no function for emailing the logs.

By default, OFCMS turns off logging of PHP errors, but does log login attempts.  Those settings can be found and changed as shown below (with defaults).

Near the top of onefilecms.php:

//Some basic security & error log settings
...
ini_set('log_errors'    , 'off');




And after the License section:


// CONFIGURABLE OPTIONS ********************************************************
...
$LOG_LOGINS    = true; //Keep log of login attempts.



OneFile will also create a backup file of itself if you use the Admin page to change either the password or username.  Existing login log or onefilecms.php backup files will also be listed and can be deleted from that page.

If this doesn't solve your issue, please feel free to re-open this issue.
Thanks!
